import subprocess, sys

prompt = (
    "You are Codex executing a bounded RIMA task. Read CODEX.md for project rules. "
    "Stay strictly inside the allowed file list.\n\n"
    "TASK: RIMA Room Designer F2 - T3A: FloorVariantPainter + WallAutoConnect\n\n"
    "ALLOWED FILES (CREATE both):\n"
    "- Assets/Editor/RoomDesigner/FloorVariantPainter.cs\n"
    "- Assets/Editor/RoomDesigner/WallAutoConnect.cs\n\n"
    "== TASK A: FloorVariantPainter.cs ==\n\n"
    "Create Assets/Editor/RoomDesigner/FloorVariantPainter.cs\n"
    "Namespace: RIMA.Editor.RoomDesigner\n"
    "Type: public static class FloorVariantPainter\n"
    "Usings: RIMA.Runtime.Rooms, UnityEngine, UnityEngine.Tilemaps\n\n"
    "Constants (private const float):\n"
    "  AccentThreshold = 0.65f\n"
    "  HeroThreshold = 0.88f\n"
    "  WarpFreq = 0.05f\n"
    "  WarpStrength = 4.0f\n"
    "  ZoneFreq = 0.05f\n"
    "  DetailFreq = 0.22f\n\n"
    "Public methods:\n"
    "  public static bool BakeVariants(Tilemap floorTilemap, RoomBlueprint bp, TileBase[] variantSet)\n"
    "  public static bool PreviewVariants(Tilemap floorTilemap, RoomBlueprint bp, TileBase[] variantSet)\n"
    "  public static void RestoreDefault(Tilemap floorTilemap, TileBase baseTile)\n\n"
    "Private helper:\n"
    "  private static bool HasHeroNeighbor(Tilemap tilemap, Vector3Int cell, RoomBlueprint bp, int seed)\n\n"
    "BakeVariants and PreviewVariants algorithm:\n"
    "Step 1: if variantSet is null or variantSet.Length == 0, return false\n"
    "Step 2: BoundsInt bounds = floorTilemap.cellBounds\n"
    "Step 3 (BakeVariants only): if bp.floorVariantIndex == null or Length != bp.roomWidth*bp.roomHeight, allocate new byte[bp.roomWidth * bp.roomHeight]\n"
    "Step 4: iterate x from bounds.xMin to bounds.xMax-1, y from bounds.yMin to bounds.yMax-1:\n"
    "  - Vector3Int cell = new Vector3Int(x, y, 0)\n"
    "  - if floorTilemap.GetTile(cell) == null, continue\n"
    "  - int seed = bp.noiseSeed\n"
    "  - float seedOffset = seed * 0.1f\n"
    "  - float wx = Mathf.PerlinNoise((x + 5.2f + seedOffset) * WarpFreq, (y + 1.3f + seedOffset) * WarpFreq) * WarpStrength\n"
    "  - float wy = Mathf.PerlinNoise((x + 9.2f + seedOffset) * WarpFreq, (y + 2.8f + seedOffset) * WarpFreq) * WarpStrength\n"
    "  - float zone = Mathf.PerlinNoise((x + wx) * ZoneFreq, (y + wy) * ZoneFreq)\n"
    "  - float detail = Mathf.PerlinNoise((x + wx + seedOffset) * DetailFreq, (y + wy + seedOffset) * DetailFreq)\n"
    "  - Determine tier: if zone < AccentThreshold => tier=0 (base), else if zone < HeroThreshold => tier=1 (accent), else tier=2 (hero)\n"
    "  - If tier==2 and HasHeroNeighbor(floorTilemap, cell, bp, seed) => tier=1 (downgrade to accent)\n"
    "  - int tierOffset, tierSize: if tier==0 => (0,8), if tier==1 => (8,5), if tier==2 => (13,3)\n"
    "  - uint hash = (uint)((x * 73856093) ^ (y * 19349663) ^ seed)\n"
    "  - int varIdx = tierOffset + (int)(hash % (uint)tierSize)\n"
    "  - floorTilemap.SetTile(cell, variantSet[varIdx])\n"
    "  - BakeVariants only: int arrIdx = (y - bp.roomOrigin.y) * bp.roomWidth + (x - bp.roomOrigin.x); if arrIdx>=0 && arrIdx<bp.floorVariantIndex.Length, bp.floorVariantIndex[arrIdx] = (byte)varIdx\n"
    "Step 5: floorTilemap.RefreshAllTiles()\n"
    "Step 6: return true\n\n"
    "HasHeroNeighbor: check all 8 neighbors (dx=-1,0,1; dy=-1,0,1; skip dx==0&&dy==0). For each neighbor (nx=cell.x+dx, ny=cell.y+dy):\n"
    "  float seedOffset2 = seed * 0.1f\n"
    "  float wx2 = Mathf.PerlinNoise((nx + 5.2f + seedOffset2) * WarpFreq, (ny + 1.3f + seedOffset2) * WarpFreq) * WarpStrength\n"
    "  float wy2 = Mathf.PerlinNoise((nx + 9.2f + seedOffset2) * WarpFreq, (ny + 2.8f + seedOffset2) * WarpFreq) * WarpStrength\n"
    "  float zone2 = Mathf.PerlinNoise((nx + wx2) * ZoneFreq, (ny + wy2) * ZoneFreq)\n"
    "  if zone2 >= HeroThreshold return true\n"
    "Return false\n\n"
    "RestoreDefault: BoundsInt b = floorTilemap.cellBounds; iterate x,y; cell = new Vector3Int(x,y,0); if GetTile(cell) != null, SetTile(cell, baseTile); then RefreshAllTiles\n\n"
    "== TASK B: WallAutoConnect.cs ==\n\n"
    "Create Assets/Editor/RoomDesigner/WallAutoConnect.cs\n"
    "Namespace: RIMA.Editor.RoomDesigner\n"
    "Type: public static class WallAutoConnect\n"
    "Usings: System.Collections.Generic, RIMA.Runtime.Rooms, UnityEngine, UnityEngine.Tilemaps\n\n"
    "Private field:\n"
    "  private static readonly Vector3Int[] NeighborOffsets = { new Vector3Int(-1,0,0), new Vector3Int(1,0,0), new Vector3Int(0,1,0), new Vector3Int(0,-1,0), new Vector3Int(-1,1,0), new Vector3Int(1,1,0), new Vector3Int(-1,-1,0), new Vector3Int(1,-1,0) }\n\n"
    "Public methods:\n"
    "  public static void RefreshNeighborhood(Tilemap wallTilemap, IEnumerable<Vector3Int> touchedCells, TileBase[] wallVariants, RoomBlueprint bp = null)\n"
    "  public static void RefreshCell(Tilemap wallTilemap, Vector3Int cell, TileBase[] wallVariants, RoomBlueprint bp = null)\n"
    "  public static bool BakeWallVariants(Tilemap wallTilemap, RoomBlueprint bp, TileBase[] wallVariants)\n\n"
    "RefreshCell:\n"
    "1. if wallTilemap.GetTile(cell) == null, return\n"
    "2. if bp != null: int cellIdx = (cell.y - bp.roomOrigin.y) * bp.roomWidth + (cell.x - bp.roomOrigin.x); if bp.overrideVariantIndex != null && cellIdx >= 0 && cellIdx < bp.overrideVariantIndex.Length && bp.overrideVariantIndex[cellIdx], return\n"
    "3. bool hasW = wallTilemap.GetTile(new Vector3Int(cell.x-1, cell.y, cell.z)) != null\n"
    "   bool hasE = wallTilemap.GetTile(new Vector3Int(cell.x+1, cell.y, cell.z)) != null\n"
    "   bool hasN = wallTilemap.GetTile(new Vector3Int(cell.x, cell.y+1, cell.z)) != null\n"
    "   bool hasS = wallTilemap.GetTile(new Vector3Int(cell.x, cell.y-1, cell.z)) != null\n"
    "   int mask = (hasW?1:0) | (hasE?2:0) | (hasN?4:0) | (hasS?8:0)\n"
    "4. int connType = mask switch:\n"
    "   10 => 0, 5 => 1, 12 => 2, 6 => 3, 9 => 4, 3 => 5, 4 => 6, 2 => 6, 8 => 7, 1 => 7, default => 0\n"
    "5. TileBase selected: if wallVariants != null && connType < wallVariants.Length => wallVariants[connType]; else if wallVariants != null, find first non-null; else null\n"
    "6. wallTilemap.SetTile(cell, selected)\n\n"
    "RefreshNeighborhood:\n"
    "1. HashSet<Vector3Int> toRefresh = new HashSet<Vector3Int>()\n"
    "2. foreach touchedCell in touchedCells: for dx=-1..1, dy=-1..1: toRefresh.Add(new Vector3Int(touchedCell.x+dx, touchedCell.y+dy, touchedCell.z))\n"
    "3. foreach cell in toRefresh: RefreshCell(wallTilemap, cell, wallVariants, bp)\n\n"
    "BakeWallVariants:\n"
    "1. if wallTilemap == null || bp == null || wallVariants == null, return false\n"
    "2. BoundsInt bounds = wallTilemap.cellBounds\n"
    "3. if bp.wallVariantIndex == null || bp.wallVariantIndex.Length != bp.roomWidth*bp.roomHeight, bp.wallVariantIndex = new byte[bp.roomWidth*bp.roomHeight]\n"
    "4. for x in bounds.xMin..bounds.xMax-1, y in bounds.yMin..bounds.yMax-1:\n"
    "   - Vector3Int cell = new Vector3Int(x,y,0)\n"
    "   - if wallTilemap.GetTile(cell) == null, skip\n"
    "   - Build mask same as RefreshCell, get connType\n"
    "   - int arrIdx = (y - bp.roomOrigin.y) * bp.roomWidth + (x - bp.roomOrigin.x)\n"
    "   - if arrIdx >= 0 && arrIdx < bp.wallVariantIndex.Length, bp.wallVariantIndex[arrIdx] = (byte)connType\n"
    "   - Set tile using same selection as RefreshCell step 5\n"
    "5. wallTilemap.RefreshAllTiles()\n"
    "6. return true\n\n"
    "== CONSTRAINTS ==\n"
    "- No comments in code except the NeighborOffsets field inline comments matching the spec\n"
    "- No new dependencies beyond listed usings\n"
    "- Must compile without errors\n\n"
    "== GIT COMMIT ==\n"
    "After writing both files run these two git commands:\n"
    "git add Assets/Editor/RoomDesigner/FloorVariantPainter.cs Assets/Editor/RoomDesigner/WallAutoConnect.cs\n"
    'git commit -m "feat(room-designer): FloorVariantPainter + WallAutoConnect domain-warp Perlin + wall auto-connect\n\nCo-Authored-By: Claude Sonnet 4.6 <noreply@anthropic.com>"\n\n'
    "REPORT FORMAT:\n"
    "STATUS: DONE / FAILED / PARTIAL\n"
    "COMPLETED: <bullets>\n"
    "ERRORS: <or NONE>\n"
    "FILES_TOUCHED: <paths>\n"
    "COMMIT: <hash>\n"
    "NEXT_SIGNAL: task-t3a-done\n"
)

cmd = [
    'C:/Users/ydbil/AppData/Roaming/npm/cx.cmd',
    'run', 'laurethgame', 'exec',
    '--skip-git-repo-check',
    '--color', 'never',
    '--dangerously-bypass-approvals-and-sandbox',
    '--config', 'model_reasoning_effort=high',
    prompt
]

result = subprocess.run(cmd, stdin=subprocess.DEVNULL, capture_output=False, text=True,
                        cwd='F:/Antigravity Projeler/2d roguelite/RIMA')
sys.exit(result.returncode)
